### ISSUE TITLE
Dewallua is not included in the release or installation instructions

### ISSUE THREAD

**Issue by Nattie-G** [Aweptimum/Strike#3]
Installing Strike as per the readme instructions leads to a crash and error due to the dewallua library not being included in the release. The github repo links to the correct files in your dewallua repo and copying them in will resolve this. however by default, the files are not included when downloading or cloning the repo.

```path: Strike.lib.DeWallua.vector-light
Error: Strike/Strike.lua:1: module 'Strike.lib.DeWallua.vector-light' not found:
	no field package.preload['Strike.lib.DeWallua.vector-light']
	no 'Strike/lib/DeWallua/vector-light' in LOVE game directories.
	no file 'Strike/lib/DeWallua/vector-light' in LOVE paths.
	no file './Strike/lib/DeWallua/vector-light.lua'
	no file '/usr/share/luajit-2.0.5/Strike/lib/DeWallua/vector-light.lua'
	no file '/usr/local/share/lua/5.1/Strike/lib/DeWallua/vector-light.lua'
	no file '/usr/local/share/lua/5.1/Strike/lib/DeWallua/vector-light/init.lua'
	no file '/usr/share/lua/5.1/Strike/lib/DeWallua/vector-light.lua'
	no file '/usr/share/lua/5.1/Strike/lib/DeWallua/vector-light/init.lua'
	no file './Strike/lib/DeWallua/vector-light.so'
	no file '/usr/local/lib/lua/5.1/Strike/lib/DeWallua/vector-light.so'
	no file '/usr/lib/lua/5.1/Strike/lib/DeWallua/vector-light.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './Strike.so'
	no file '/usr/local/lib/lua/5.1/Strike.so'
	no file '/usr/lib/lua/5.1/Strike.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[string "boot.lua"]:777: in function <[string "boot.lua"]:773>
	[C]: in function '_Require_relative'
	Strike/Strike.lua:1: in main chunk
	[C]: in function 'require'
	Strike/init.lua:26: in main chunk
	[C]: in function 'require'
	main.lua:1: in main chunk
	[C]: in function 'require'
	[string "boot.lua"]:570: in function <[string "boot.lua"]:380>
	[C]: in function 'xpcall'
	[string "boot.lua"]:787: in function <[string "boot.lua"]:780>
	[C]: in function 'xpcall'```

**Comment by Aweptimum** [comment]
You're right! The installation instructions are lacking.
I think adding this to the Installation section should be enough to prevent others from experiencing this:
> If using git's command line to clone Strike, run either of the following commands to clone it:
`git clone --recurse-submodules https://github.com/Aweptimum/Strike.git` (git >= 2.13)
`git clone --recursive https://github.com/Aweptimum/Strike.git` (git < 2.13)
If using github desktop, it automatically resolves submodules, so no command-line needed

**Comment by Nattie-G** [comment]
I tested cloning the repo using the ```--recursive-submodules``` flag in git v 2.33.0 and can confirm it fetches the dewallua lib as desired, resolving the issue!
