### ISSUE TITLE
shapes:getPoints() / collider:getPoints()

### ISSUE THREAD

**Issue by togfoxy** [Aweptimum/Strike#30]
Would be great to be able to get the points for reading/checking/fault finding etc.

Thanks!

**Comment by Aweptimum** [comment]
I can definitely add a method to the VertexShape class, but I'm not sure it makes sense to add it to the Collider class 🤔 since there are potentially multiple shapes within a collider. I know a lot of the base ones don't have multiple shapes, but the Collider class is like a tree node. It was meant to provide a way to group multiple shapes together, mainly so concave polygons could be decomposed and treated like anything else

**Comment by togfoxy** [comment]
My use case:

I draw all sorts of things during love.draw() and on my current project I scale everything by 5 (x5) because makes sense. I have an object that is displayed at x * 5 and y * 5 and it appears 5 times as large. I do NOT adjust the original / real x/y co-ordinates. My scaling happens during draw routines only. This way, vector maths and manipulations happen at 1:1 and the drawing explodes this to 5:1 (of course the 5:1 is arbitrary).

My objects have a collider but collider:draw() will, naturally, draw 1:1. This means all my colliders are draw in the top left corner of the screen and are totally out of sync with what is being drawn elsewhere.

If I could interogate the points of the collider/shapes (not sure what is best) then I could also render those 5:1 onto the screen during love.draw() and the colliders once again align with the drawn images.

It is the same principle as box2d meter property. It defaults to 30 and scales everything by 30. I'm using the same principle during my draw routine.

Clearly, this is for debugging only. Thanks.

**Comment by Aweptimum** [comment]
Added a pr for this

Out of curiosity, are you using love's transformations or are you manually passing in the scaling to each draw call?

**Comment by togfoxy** [comment]
I do it inside love.graphics.draw(). In the below example, DRAWSCALE is a constant. I set it to 1 (1:1) to debug colliders then set it to 5 (5:1) to debug the game as it's intended to look and feel.

`
love.graphics.draw(IMAGE[obj.imageenum], obj.x * DRAWSCALE, obj.y * DRAWSCALE, facingrad, xscale * DRAWSCALE, yscale * DRAWSCALE, xoffset, yoffset)
`

My code is open source FYI: https://codeberg.org/togfox/WW2SubCombat/src/branch/main/source

**Comment by Aweptimum** [comment]
I think the problem then is that you're not scaling the drawn colliders. And there's not a parameter for that :(
(There used to be, but I removed it when I added geometry transforms.)

What you might be able to do is this:
```lua
love.graphics.scale( DRAWSCALE , DRAWSCALE )
collider:draw()
love.graphics.scale( 1, 1 )
```
Although I'm not sure if that'll position it properly 🤔

I could look into trying to add the scaling back.

**Comment by togfoxy** [comment]
That actually works!!  :)

I'm satisfied with this. TYVM!

**Comment by Aweptimum** [comment]
Ok, cool! I'll still merge the pr, but closing this.
